plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 33

    defaultConfig {
        applicationId "com.guptaadarsh.ytwrapper"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 4
        versionName "4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // Zero heavy dependencies to keep APK under 2MB and RAM under 20MB
    implementation 'org.nanohttpd:nanohttpd:2.3.1'
}
