plugins {
    id 'com.android.application'
}

android {
    namespace 'com.yourname.ytwrapper'
    compileSdk 33

    defaultConfig {
        applicationId "com.yourname.ytwrapper"
        minSdk 19
        targetSdk 19
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

